### ISSUE TITLE
Angelscript: Plugin script compilation failed

### ISSUE THREAD

**Issue by RedyRT** [Neyami/CSO-Weapons#4]
ERROR: Angelscript: d:/sven-coopserver/svencoop/scripts/custom_weapons/cso/weapon_augex.as (308, 69) : No matching symbol 'SMOKE_AUGEX'
ERROR: Angelscript: Plugin script compilation failed
![изображение](https://github.com/Neyami/CSO-Weapons/assets/64935439/95ae1db4-089c-46e1-98ea-cc2ac3332371)

**Comment by Neyami** [comment]
Yeah I'm updating that atm, just remove lines 307 through 312 for now :ayaya:
