### ISSUE TITLE
Warnings + 1 Error

### ISSUE THREAD

**Issue by RedyRT** [Neyami/CSO-Weapons#5]
Warning:  Unable to open sprites/custom_weapons/cso/weapon_aug.txt for transfer
Warning:  Unable to open sprites/custom_weapons/cso/weapon_augex.txt for transfer
Warning:  Unable to open sprites/custom_weapons/cso/sniper_scope.spr for transfer
Warning:  Unable to open models/custom_weapons/cso/w_50bmg.mdl for transfer

WARNING:  HUD: Invalid channel group #-1weapon_bloodhunter has been destroyed via ~

Error: 'models/custom_weapons/cso/w_50bmg.mdl' not found, swapping it for 'models/error.mdl'.

**Comment by Neyami** [comment]
Wups, thanks! :ayaya:
The bloodhunter thing isn't a problem, it's just leftover debug stuff I forgot to remove :ayaya:
The invalid channel group I'm not sure about though 🤔 

Thanks for reporting on these btw, sometimes I miss uploading stuff :hehe:
